### PR TITLE
Handle the version in the standard go way

### PR DESCRIPTION
**Pull request by geoand**
The version and git commit are set during the build with `ldflags`

### CODE REVIEW

**Comment by geoand** [comment]
The `Makefile` is already setup to include the version and commit sha in the way that is described [here](https://github.com/golang/go/wiki/GcToolchainTricks#including-build-information-in-the-executable)

**Comment by cmoulliard** [comment]
So, we only need the `// VERSION` line ? @geoand

**Comment by geoand** [comment]
@cmoulliard No, we need the `VERSION` variable that is defined inside var (... )

**Comment by geoand** [comment]
That is what get's set by `ldflags`

**Pull request merged**
